# Generated by Django 4.0 on 2021-12-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='postname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='champion',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
