# Generated by Django 4.0 on 2022-01-13 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='champion',
            old_name='postname',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='champion',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='champion',
            old_name='contents',
            new_name='type',
        ),
    ]
