# Generated by Django 4.0 on 2022-01-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_rename_postname_champion_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
